queue_rules:
  - name: dependabot
    queue_conditions:
      - author=dependabot[bot]
    merge_conditions:
      - author=dependabot[bot]
      - status-success=test
      - status-success=lint
      - base=master
    merge_method: squash

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
