require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss-configs.gemspec

RSpec/DescribeClass:
  Exclude:
    - "spec/html2rss/configs/**/*.yml_spec.rb"
    - "spec/bin/*_spec.rb"

Style/Documentation:
  Enabled: false
