require:
  - rubocop-rspec
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss-configs.gemspec

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/html2rss/configs/**/*.yml_spec.rb"
    - "spec/bin/*_spec.rb"
