require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss-configs.gemspec

Metrics/MethodLength:
  CountAsOne:
    - heredoc

RSpec/DescribeClass:
  Exclude:
    - "spec/html2rss/configs/**/*.yml_spec.rb"
    - "spec/bin/*_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassStructure:
  Enabled: true

