require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - html2rss-configs.gemspec

Layout/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - "spec/html2rss/configs/**/*.yml_spec.rb"
    - "spec/bin/*_spec.rb"
