require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - vendor/**/*

Layout/ClassStructure:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - "spec/html2rss/configs/**/*.yml_spec.rb"

Naming/RescuedExceptionsVariableName:
  PreferredName: error
