sudo: false
language: ruby
cache: bundler

before_install:
  - sudo apt-get install -y yamllint yarn
  - gem update --system
  - gem install bundler
  - yarn install

bundler_args: "--jobs=3 --retry=3"

script:
  - make lint
  - make test
  - make test-fetch-changed-configs

deploy:
  provider: script
  script: bin/ci-build-html2rss-web
  on:
    branch: master
