sudo: false
language: ruby
cache: bundler

before_install:
  - sudo apt-get install -y yamllint
  - gem update --system
  - gem install bundler

bundler_args: "--jobs=3 --retry=3"

rvm:
  - 2.4.6
  - 2.5.4
  - 2.6.3

script:
  - make lint
  - make test
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then make test_changed_configs; fi'
