name: Ruby

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: yarn

      - name: Install dependencies
        run: |
          sudo apt-get install -yqq yamllint
          yarn install --frozen-lockfile --no-progress --non-interactive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true

      - name: Run linters
        run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, "3.0"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: make test

  test_changed_configs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true

      - name: setup remote origin
        run: >-
          git remote set-url origin
          https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Test changed configs with fetching
        run: |
          git fetch origin master --depth 1
          make test-fetch-changed-configs
