name: Ruby

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install dependencies
        run: |
          sudo apt-get install -yqq yamllint
          bundle config path vendor/bundle
          bundle config --global frozen 1
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile --no-progress --non-interactive

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test

      - name: setup remote origin
        run: >-
          git remote set-url origin
          https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Test changed configs with fetching
        run: |
          git fetch origin master --depth 1
          make test-fetch-changed-configs
